/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-Present by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.appc.titanium.socketio;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollFunction;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.util.TiConvert;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;

import io.socket.client.Ack;
import io.socket.client.Socket;
import io.socket.client.Manager;
import io.socket.emitter.Emitter.Listener;

@Kroll.proxy(creatableInModule=TiSocketioModule.class)
public class SocketClientProxy extends KrollProxy
{
	// Standard Debugging variables
	private static final String LCAT = "SocketIOClientProxy";
	private static final boolean DBG = TiConfig.LOGD;

	private Socket socket;
	private SocketManagerProxy manager;
	private int listenerId = 0;
	private HashMap<Integer, Listener> listeners;
	private HashMap<String, HashSet<Integer>> eventListenerIds;

	// Constructor
	public SocketClientProxy(Socket socket, SocketManagerProxy manager)
	{
		super();

		this.socket = socket;
		this.manager = manager;

		this.listeners = new HashMap<Integer, Listener>();
		this.eventListenerIds = new HashMap<String, HashSet<Integer>>();
	}

	// Properties
	@Kroll.getProperty
	public String getId()
	{
		return this.getConnected() ? this.socket.id() : null;
	}

	@Kroll.getProperty
	public boolean getConnected()
	{
		return this.socket.connected();
	}

	@Kroll.getProperty
	public SocketManagerProxy getIo()
	{
		return this.manager;
	}

	// Methods
	@Kroll.method
	public void open()
	{
		this.socket.open();
	}

	@Kroll.method
	public void connect()
	{
		this.socket.connect();
	}

	@Kroll.method
	public int _nativeOn(final String eventName, final KrollFunction callback) {
		Listener listener = new Listener() {
			@Override
			public void call(Object... args)
			{
				if (eventName.equals("reconnect_attempt")) {
					Log.d(LCAT, "reconnect_attempt " + args[0]);
				}
				callback.call(getKrollObject(), convertArguments(args));
			}
		};
		this.socket.on(eventName, listener);
		this.listeners.put(++this.listenerId, listener);
		HashSet<Integer> listenerIds = this.eventListenerIds.get(eventName);
		if (listenerIds == null) {
			listenerIds = new HashSet<Integer>();
			this.eventListenerIds.put(eventName, listenerIds);
		}
		listenerIds.add(this.listenerId);
		return this.listenerId;
	}

	@Kroll.method
	public SocketClientProxy _nativeOff(Object[] args)
	{
		if (args.length == 0) {
			this.socket.off();
			this.listeners.clear();
		} else if (args.length == 1) {
			String eventName = TiConvert.toString(args[0]);
			this.socket.off(eventName);
			HashSet<Integer> listenerIds = this.eventListenerIds.get(eventName);
			if (listenerIds != null) {
				for (Integer listenerId : listenerIds) {
					this.listeners.remove(listenerId);
				}
				this.eventListenerIds.remove(eventName);
			}
		} else if (args.length == 2) {
			String eventName = TiConvert.toString(args[0]);
			int listenerId = TiConvert.toInt(args[1]);
			Listener listener = this.listeners.get(listenerId);
			this.socket.off(eventName, listener);
			this.listeners.remove(listenerId);
			HashSet<Integer> listenerIds = this.eventListenerIds.get(eventName);
			if (listenerIds != null) {
				listenerIds.remove(listenerId);
			}
		}

		return this;
	}

	@Kroll.method
	public SocketClientProxy emit(String eventName, Object... args)
	{
		KrollFunction ackCallback = null;
		ArrayList<Object> data = new ArrayList<>();

		if (args.length > 0) {
			int lastArgumentIndex = args.length - 1;

			if (args[lastArgumentIndex] instanceof KrollFunction) {
				ackCallback = (KrollFunction)args[lastArgumentIndex];
				lastArgumentIndex -= 1;
			}

			for (int i = 0; i <= lastArgumentIndex; i++) {
				data.add(this.convertAndSanitizePayload(args[i]));
			}
		}

		if (ackCallback != null) {
			final KrollFunction finalAckCallback = ackCallback;
			this.socket.emit(eventName, data.toArray(), new Ack() {
				@Override
				public void call(Object... args) {
					finalAckCallback.call(getKrollObject(), convertArguments(args));
				}
			});
		} else {
			this.socket.emit(eventName, data.toArray());
		}

		return this;
	}

	@Kroll.method
	public void close() {
		this.disconnect();
	}

	@Kroll.method
	public void disconnect() {
		this.socket.disconnect();
	}

	private Object[] convertArguments(Object[] args) {
		Object[] sanitizedArgs = new Object[args.length];

		for (int i = 0; i < args.length; i++) {
			if (args[i] instanceof Exception) {
				Exception socketException = (Exception)args[i];
				KrollDict errorDict = new KrollDict();
				errorDict.put("message", socketException.getMessage());
				sanitizedArgs[i] = errorDict;
			} else if (args[i] instanceof JSONObject) {
				JSONObject json = (JSONObject)args[i];
				try {
					sanitizedArgs[i] = new KrollDict(json);
				} catch (JSONException e) {
					Log.d(LCAT, "Failed to convert JSON object. Error: " + e.getMessage());
					sanitizedArgs[i] = null;
				}
			} else if (args[i] instanceof JSONArray) {
				JSONArray json = (JSONArray)args[i];
				sanitizedArgs[i] = KrollDict.fromJSON(json);
			} else {
				sanitizedArgs[i] = args[i];
			}
		}

		return sanitizedArgs;
	}

	private Object convertAndSanitizePayload(Object value) {
		if (value instanceof HashMap) {
			return TiConvert.toJSON((HashMap)value);
		} else if (value instanceof Object[]) {
			return TiConvert.toJSONArray((Object[])value);
		}

		return value;
	}
}
